"""add interview session foreign keys

Revision ID: 83aba27d70df
Revises: b39909f765ee
Create Date: 2026-08-17 19:03:41.469945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83aba27d70df'
down_revision: Union[str, Sequence[str], None] = 'b39909f765ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'interview_sessions', 'candidates', ['candidate_id'], ['candidate_id'])
    op.create_foreign_key(None, 'interview_sessions', 'interview_templates', ['template_id'], ['template_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    # ### end Alembic commands ###
